### PR TITLE
fixed incorrect alias names

### PR DESCRIPTION
**Pull request by svycka**
more on this zendframework/zend-servicemanager#50

### CODE REVIEW

**Comment by weierophinney** [comment]
Both are required to allow both v2 and v3 usage; can you update to include both, please?

**Comment by svycka** [comment]
@weierophinney updated, is it ok?

**Comment by svycka** [comment]
not sure about this:
```php
    protected $invokableClasses = [
        'arrayserializable' => 'Zend\Hydrator\ArraySerializable',
        'classmethods'      => 'Zend\Hydrator\ClassMethods',
        'objectproperty'    => 'Zend\Hydrator\ObjectProperty',
        'reflection'        => 'Zend\Hydrator\Reflection'
    ];
```
maybe also add aliases?

**Comment by weierophinney** [comment]
@svycka That should be broken into aliases and factories (using `InvokableFactory`). The factory definitions should have both FQCN and canonicalized name keys; all short names should be defined as aliases, pointing to the FQCN, and should be done as all lowercase, camelCase, and TitleCase to hit the majority of use cases.

**Comment by svycka** [comment]
@weierophinney one more question should I add `validate()` method to support v3? or this should be done in another PR with all other changes for SMv3?

**Comment by svycka** [comment]
Also not sure if I can use `::class` here.

**Comment by weierophinney** [comment]
> Also not sure if I can use ::class here.

Absolutely; minimum PHP version is 5.5, which is the version introducing that magic constant. :smile:

**Comment by weierophinney** [comment]
> one more question should I add validate() method to support v3? or this should be done in another PR with all other changes for SMv3?

Go ahead and do it in this one, and change the title to reflect that it's doing a full v2/v3 compatibility changeset.

**Comment by svycka** [comment]
@weierophinney I think @kynx did a lot of work for V3 support in https://github.com/zendframework/zend-hydrator/pull/17 so I think I will not duplicate the same :-)

**Pull request closed without merging**
